spring.application.name=apirest
server.address=0.0.0.0
server.port=8080

spring.datasource.url=jdbc:mysql://tokaido.proxy.rlwy.net:43018/railway?createDatabaseIfNotExist=true&useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&sslMode=REQUIRED
spring.datasource.username=root
spring.datasource.password=jfkYIbCSpGAGucWdLgHpyHkdeGRgZhLM
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
