spring.application.name=apirest
server.address=0.0.0.0
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

python.service.url=${PYTHON_SERVICE_URL:}
python.ml.url=${PYTHON_ML_URL:}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:*}

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
